#!/bin/sh

#
# Copyright 2014-2015-2015 Sandia Corporation. Under the terms of Contract
# DE-AC04-94AL85000, there is a non-exclusive license for use of this work
# by or on behalf of the U.S. Government. Export of this program may require
# a license from the United States Government.
#
# This file is part of the Power API Prototype software package. For license
# information, see the LICENSE file in the top level directory of the
# distribution.
#

prefix=/global/home/hpc5573/pwrapi-ref/build/install

export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${prefix}/lib"
export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${prefix}/lib"

export POWERAPI_DEBUG=0
export POWERAPI_ROOT="plat.node0"
export POWERAPI_CONFIG="./hwloc_cac.xml"

export PATH="$PATH:${prefix}/lib"
